# Pure policy and injectable platform adapters for the Windows logon supervisor.
function Get-SupervisorKey([string]$Workspace, [int]$Port) {
  $sha = [Security.Cryptography.SHA256]::Create()
  try { return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Workspace.ToLowerInvariant() + ':' + $Port)))).Replace('-', '').Substring(0, 24) } finally { $sha.Dispose() }
}
function Enter-SupervisorLock([string]$Key) {
  # Global namespace covers different logon sessions; state directory is deliberately absent.
  $mutex = New-Object Threading.Mutex($false, ('Global\C2C-Supervisor-' + $Key))
  try { $held = $mutex.WaitOne(0) } catch [Threading.AbandonedMutexException] { $held = $true }
  if (-not $held) { $mutex.Dispose(); return $null }
  return $mutex
}
function Get-BridgeIdentity($Process) {
  if (-not $Process -or -not $Process.CreationDate -or -not $Process.CommandLine) { return $null }
  return ('{0}|{1}|{2}' -f $Process.ProcessId, $Process.CreationDate.ToUniversalTime().Ticks, $Process.CommandLine)
}
function Test-BridgeCommand($Process, $Config) {
  if (-not $Process) { return $false }
  # The only accepted argv forms are those generated by this supervisor or the repo daemon.
  $entry = [regex]::Escape($Config.CliEntry)
  $workspace = [regex]::Escape($Config.Workspace)
  $port = $Config.LocalPort
  return $Process.CommandLine -match ('^(?:"[^"]*node(?:\.exe)?"|\S*node(?:\.exe)?)\s+"?' + $entry + '"?\s+serve\s+--workspace\s+(?:"' + $workspace + '"|' + $workspace + ')(?:\s+--port\s+' + $port + ')?\s*$')
}
function New-SupervisorState {
  return @{ Failures = 0; Attempts = 0; NextAttempt = 0; Owned = $null; LastReason = ''; HealthyTicks = 0 }
}
function Invoke-SupervisorTick($Config, $State, $Adapters, [double]$Now) {
  try {
  $runtime = & $Adapters.Runtime
  $listener = @(& $Adapters.Listener)
  $health = & $Adapters.Health
  $status = & $Adapters.Status
  $process = if ($runtime) { & $Adapters.Process $runtime.pid } else { $null }
  $identity = Get-BridgeIdentity $process
  $portMatches = $runtime -and $runtime.port -eq $Config.LocalPort
  $trusted = $portMatches -and $runtime.workspaceId -eq $Config.WorkspaceId -and
    $runtime.workspaceRoot -eq $Config.Workspace -and $listener.Count -eq 1 -and
    $listener[0] -eq $runtime.pid -and (Test-BridgeCommand $process $Config)
  # startedAt is written after the process starts; reject stale files from PID reuse.
  if ($trusted) {
    try { $age = ([datetime]$runtime.startedAt).ToUniversalTime() - $process.CreationDate.ToUniversalTime(); $trusted = $age.TotalSeconds -ge -2 -and $age.TotalSeconds -le 120 } catch { $trusted = $false }
  }
  $healthy = $trusted -and $health -and $health.status -eq 'ok' -and
    $health.workspaceId -eq $Config.WorkspaceId -and $status -and $status.ok -eq $true -and
    $status.running -eq $true -and $status.pid -eq $runtime.pid -and
    $status.port -eq $Config.LocalPort -and $status.workspaceId -eq $Config.WorkspaceId -and
    $status.workspaceRoot -eq $Config.Workspace
  if ($healthy) {
    $State.Owned = $identity; $State.Failures = 0; $State.HealthyTicks++
    # A brief successful probe must not erase a restart storm's backoff.
    if ($State.HealthyTicks -ge 12) { $State.Attempts = 0; $State.NextAttempt = 0 }
    $reason = 'healthy'
  } else {
    $State.HealthyTicks = 0; $State.Failures++
    $runtimeAbsent = -not $runtime -or (-not $process -and $portMatches -and $runtime.workspaceId -eq $Config.WorkspaceId -and $runtime.workspaceRoot -eq $Config.Workspace)
    $empty = $listener.Count -eq 0 -and -not $health -and $runtimeAbsent
    $owned = $trusted -and $identity -and $State.Owned -eq $identity
    $reason = if ($runtime -and -not $portMatches) { 'port-mismatch' } elseif ($empty) { 'stopped' } elseif ($owned) { 'owned-degraded' } else { 'untrusted-state' }
    if (($empty -or $owned) -and $State.Failures -ge $Config.FailureThreshold -and $Now -ge $State.NextAttempt) {
      $State.Attempts++; $State.NextAttempt = $Now + [Math]::Min($Config.MaxBackoffSeconds, $Config.InitialBackoffSeconds * [Math]::Pow(2, [Math]::Min(10, $State.Attempts - 1)))
      try {
        & $Adapters.Backup
        if ($owned) {
          # Recheck immediately before stopping: no cached PID can authorize a kill.
          $current = & $Adapters.Process $runtime.pid
          $currentListeners = @(& $Adapters.Listener)
          if ((Get-BridgeIdentity $current) -ne $State.Owned -or $currentListeners.Count -ne 1 -or $currentListeners[0] -ne $runtime.pid) { throw 'identity-changed' }
          & $Adapters.Stop $runtime.pid $State.Owned
          $State.Owned = $null
        }
        # Start adapter independently rechecks vacancy; CLI serve is explicitly port-bound.
        & $Adapters.Start
        $reason = 'recovery-started'
      } catch { $reason = 'recovery-refused' }
    }
  }
  if ($State.LastReason -ne $reason) { & $Adapters.Log $reason; $State.LastReason = $reason }
  # This check runs on every tick even while SSH remains alive or bridge probes fail.
  return $reason
  } finally { & $Adapters.Ssh $Now }
}
function Invoke-BoundedProcess([string]$File, [string]$Arguments, [string]$StateDirectory, [int]$TimeoutSeconds = 10) {
  $info = New-Object Diagnostics.ProcessStartInfo
  $info.FileName = $File; $info.Arguments = $Arguments; $info.UseShellExecute = $false; $info.CreateNoWindow = $true
  $info.RedirectStandardOutput = $true; $info.RedirectStandardError = $true
  if ($StateDirectory) { $info.EnvironmentVariables['C2C_STATE_DIR'] = $StateDirectory }
  $child = New-Object Diagnostics.Process
  $child.StartInfo = $info
  try {
    [void]$child.Start()
    $stdout = $child.StandardOutput.ReadToEndAsync(); $stderr = $child.StandardError.ReadToEndAsync()
    if (-not $child.WaitForExit($TimeoutSeconds * 1000)) { $child.Kill(); [void]$child.WaitForExit(2000); return $null }
    if ($child.ExitCode -ne 0) { return $null }
    return $stdout.Result
  } finally { $child.Dispose() }
}
function Backup-BridgeState([string]$StateDirectory, [string]$WorkspaceId) {
  $folder = Join-Path $StateDirectory ('supervisor-backups\' + [guid]::NewGuid().ToString('N'))
  [void](New-Item -ItemType Directory -Path $folder -Force -ErrorAction Stop)
  $sid = [Security.Principal.WindowsIdentity]::GetCurrent().User
  $acl = New-Object Security.AccessControl.DirectorySecurity
  $acl.SetAccessRuleProtection($true, $false)
  $acl.SetOwner($sid)
  $rule = New-Object Security.AccessControl.FileSystemAccessRule($sid, 'FullControl', 'ContainerInherit,ObjectInherit', 'None', 'Allow')
  $acl.AddAccessRule($rule)
  Set-Acl -LiteralPath $folder -AclObject $acl -ErrorAction Stop
  foreach ($kind in @('auth', 'runtime')) {
    $source = Join-Path $StateDirectory ($kind + '\' + $WorkspaceId + '.json')
    if (Test-Path -LiteralPath $source) {
      $destination = Join-Path $folder ($kind + '.json')
      Copy-Item -LiteralPath $source -Destination $destination -ErrorAction Stop
      # Copy-Item may retain a source ACL: explicitly enforce the protected parent ACL.
      $fileAcl = New-Object Security.AccessControl.FileSecurity
      $fileAcl.SetOwner($sid); $fileAcl.SetAccessRuleProtection($true, $false)
      $fileAcl.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($sid, 'FullControl', 'Allow')))
      Set-Acl -LiteralPath $destination -AclObject $fileAcl -ErrorAction Stop
      if ((Get-FileHash -LiteralPath $source).Hash -ne (Get-FileHash -LiteralPath $destination).Hash) { throw 'backup-verification-failed' }
    }
  }
  return $folder
}
function Wait-SupervisedChild($Child, $Identity, $Config, $Adapters, [int]$Checks = 40) {
  $ready = $false
  try {
    for ($index = 0; $index -lt $Checks; $index++) {
      if ($Child.HasExited) { throw 'child-exited' }
      $runtime = & $Adapters.Runtime
      if ($runtime -and $runtime.pid -eq $Child.Id) {
        if ($runtime.port -ne $Config.LocalPort -or $runtime.workspaceId -ne $Config.WorkspaceId) { throw 'child-runtime-mismatch' }
        $listeners = @(& $Adapters.Listener)
        if ($listeners.Count -eq 1 -and $listeners[0] -eq $Child.Id) { $ready = $true; return }
      }
      & $Adapters.Delay
    }
    throw 'child-start-timeout'
  } finally {
    $current = & $Adapters.Process $Child.Id
    if (-not $ready -and (Get-BridgeIdentity $current) -eq $Identity -and (Test-BridgeCommand $current $Config)) {
      & $Adapters.Stop $Child.Id $Identity
    }
  }
}
